# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import newapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0010_auto_20170508_1941'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(null=True, upload_to=newapp.models.upload_image),
        ),
    ]
